version: '3.8'

services:
  # MongoDB for main application data
  mongodb:
    image: mongo:7.0
    container_name: qwipo-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: qwipo123
      MONGO_INITDB_DATABASE: qwipo_recommendations
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - qwipo-network

  # Redis for caching and sessions
  redis:
    image: redis:7.2-alpine
    container_name: qwipo-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - qwipo-network

  # Backend API service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: qwipo-backend
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGODB_URI: mongodb://admin:qwipo123@mongodb:27017/qwipo_recommendations?authSource=admin
      REDIS_URL: redis://redis:6379
      AI_SERVICE_URL: http://ai-service:8000
      JWT_SECRET: qwipo_jwt_secret_key_2024
      FRONTEND_URL: http://localhost:3000
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - qwipo-network

  # AI/ML Recommendation service
  ai-service:
    build:
      context: ./ai-service
      dockerfile: Dockerfile
    container_name: qwipo-ai-service
    restart: unless-stopped
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MONGODB_URI: mongodb://admin:qwipo123@mongodb:27017/qwipo_recommendations?authSource=admin
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./ai-service:/app
    networks:
      - qwipo-network

  # Frontend React application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: qwipo-frontend
    restart: unless-stopped
    environment:
      REACT_APP_API_URL: http://localhost:5000/api
      REACT_APP_AI_SERVICE_URL: http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - qwipo-network

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: qwipo-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
      - ai-service
    networks:
      - qwipo-network

volumes:
  mongodb_data:
  redis_data:

networks:
  qwipo-network:
    driver: bridge